### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by andre-dierker** [schaal/ocreader#1]
Every time I try to update, Ocreader throws a exception. 
![screenshot_20160215-123038](https://cloud.githubusercontent.com/assets/6938843/13047609/91dee31a-d3e0-11e5-9401-b59548f9b912.png)

Andre

**Comment by schaal** [comment]
What's your owncloud news version?

**Comment by schaal** [comment]
I added a null check in the JSON parsing code, hopefully this fixes this issue, will release a new beta soon.

**Comment by andre-dierker** [comment]
Everything is working fine. Nice work btw. 
Greetings Andre
