### ISSUE TITLE
action mode icons not visible in light mode

### ISSUE THREAD

**Issue by maurerle** [schaal/ocreader#105]
## Description of the issue
In the former version one could mark articles above a selected one as read. This was very useful if you skimmed over the headlines of a lot of articles and want to mark them as read as you don't want to read them all (for Newstickers and stuff like this).

Could you please provide this functionality in the new version again?
Thank you for maintaining this app! 👍 

## Your Environment

* OCReader version: v0.48
* Nextcloud news version: 
* Android version: 10

**Comment by schaal** [comment]
This should still work by long-pressing an article and selecting the action from the top action menu

**Comment by maurerle** [comment]
You are right, it works.
But the Top buttons are not visible when using light mode.
Using dark mode i could see them.
