### ISSUE TITLE
Changing article when scrolling 

### ISSUE THREAD

**Issue by lazerleif** [schaal/ocreader#108]
## Description of the issue
When i scroll in an article it is so easy that i change the article when scrolling down. The app thinks that im sliding to the side.
Maybe just me but it happens alot to me.
Otherwise a really good app!

Oneplus 6, with LineageOS 16
OCreader v. 0.52 from fdroid

**Comment by schaal** [comment]
I changed the implementation to viewpager2 as the original viewpager is deprecated. Unfortunately this doesn't work very well with the webview displaying the article (see also https://issuetracker.google.com/issues/139867645).
