### ISSUE TITLE
Option to "view image" and view image title

### ISSUE THREAD

**Issue by kuba-orlik** [schaal/ocreader#11]
Hi! I love the app! It's become my default RSS reader. There's one option I'm missing, though: when reading comics, I'd like to be able to zoom in on them, as well as to see the image title (where punchline is often stored, xkcd-style). 

Here's how I imagine it: you double-tap or press-and-hold on an image and you go to Image View, which works as if you were browsing an image in an image gallery. There's a "..." icon that you can tap to reveal the image title.

**Comment by schaal** [comment]
For the zoom part I can just enable zoom directly on the article page.

The title part I think is better handled on the server side. Nextcloud news uses picoFeed to parse the rss feeds, which has support for site-specific rules, e.g. for xkcd it converts the image title into text underneath the image. You could file a bug on https://github.com/fguillot/picoFeed to get support for your comics added.

**Comment by kuba-orlik** [comment]
> For the zoom part I can just enable zoom directly on the article page.

That would be awesome!

I'll file an issue @ picoFeed, thanks for the heads-up!
