### ISSUE TITLE
OCReader stopped working, started giving error after NextCloud News App update

### ISSUE THREAD

**Issue by theJoshMuller** [schaal/ocreader#115]
## Description of the issue

OCReader was working great with my NC instance until I updated to News 16.0.0. After I updated, all my devices I use OCReader on offer a `Nextcloud News not installed or version not supported. Please install or update to at least %s` error whenever I try to pull down new posts.

## Expected behavior

No error; normal functionality

## Steps to reproduce

Not sure if this is other's experiences, but my experience was:
1. System working fine
2. Update News app from 15.x.x to 16.0.0
3. OCReader's connectivity breaks

## Your Environment

* OCReader version: F-droid current: 0.56
* Nextcloud news version: 16.0.0
* Android version: Multiple (tablet, phone, etc.). My phone is Android 10.

**Comment by schaal** [comment]
I just released version 0.57 which should fix this issue, it will take a few days until it appears on F-Droid

**Comment by joshdm42** [comment]
Thanks so much.

**Comment by joshdm42** [comment]
Issue fixed on most recent OCReader Update. 

Thanks, @schaal !

**Comment by joshdm42** [comment]
Just checking: there's a new update for the NC News app. This bug won't be a problem for future updates, right? I don't want to update my News app yet if it'll break ocreader

**Comment by schaal** [comment]
Just tested it and it works with the new version. Minor updates (e.g. from 16.0.0 to 16.0.1) shouldn't be a problem usually.

**Comment by joshdm42** [comment]
Hi @schaal and all!

News 17.0.0 was just released.

Wondering if this bug will be an issue, or can I update without concern?

Thanks!
