### ISSUE TITLE
Feature Request: Dark Theme

### ISSUE THREAD

**Issue by tux93** [schaal/ocreader#15]
So far the App works like a charm so good work on that, but for me It'd be even better if there was an option to get a dark theme similar to what the ownCloud News App has

**Comment by schaal** [comment]
If it isn't too much work I'll try to add DayNight mode: https://medium.com/@chrisbanes/appcompat-v23-2-daynight-d10f90c83e94#.ts87gosg1 which gives a Dark theme almost for free, but it might be a while until I get to it.

**Comment by schaal** [comment]
With version 0.23 the app theme can be changed to a dark theme.
