### ISSUE TITLE
App doesn't work

### ISSUE THREAD

**Issue by tapir** [schaal/ocreader#16]
Whenever I install OCReader it works for the first 2-3 times and then I start getting this error:
![photo_2016-09-08_15-10-34](https://cloud.githubusercontent.com/assets/223984/18348889/bdffd25e-75d6-11e6-89b1-7a474f3c07aa.jpg)

It was tested on ownCloud 9, NextCloud 9 and 10.

**Comment by schaal** [comment]
Not sure what's happening there, the item url shouldn't be NULL.

What version of the news app are you running on the server?

Would you be ok with sending me the output of the command
```
curl -u <username> https://<cloudserver>/index.php/apps/news/api/v1-2/items
```
This returns a list of your unread items, so I can try and figure out what's wrong.

**Comment by schaal** [comment]
I released a new version with a possible fix, should be on f-droid tomorrow or so

**Comment by tapir** [comment]
it works thanks
