### ISSUE TITLE
Sort by "published | pub_date" for "item"

### ISSUE THREAD

**Issue by thfree** [schaal/ocreader#19]
Hello!

Take as an example of this:
``
https://www.youtube.com/feeds/videos.xml?playlist_id=PLQCYG6lKBuTarUZhGcIw8RzkPGcPAAIef
``

Due to the fact that there is constantly updated
``
<Updated> *** </ updated>
``

With sorting problems, such 'ITEM' always on top.

Could you implement sorting by date 'ITME' in Nextcloud.

Or to make the switch to the type of sorting.

**Comment by schaal** [comment]
It's actually already sorted by the published date, so I don't know what's going on there

**Comment by thfree** [comment]
![tmp_9285-screenshot_2016-09-26-17-58-46-1752389047](https://cloud.githubusercontent.com/assets/13134495/18839357/be5437ba-841b-11e6-84a0-0c10f7f5efe2.png)

**Comment by thfree** [comment]
and so every 15 minut, in the web interface has no such problem.

**Comment by thfree** [comment]
![tmp_9285-img_20160926_181251697443628](https://cloud.githubusercontent.com/assets/13134495/18839785/4c03f928-841d-11e6-9511-e0369eff195e.jpg)

**Comment by schaal** [comment]
This seems to be related to this issue: https://github.com/owncloud/news/issues/982
A fix is already implemented in https://github.com/fguillot/picoFeed/pull/268 but not yet in Nextcloud News

**Comment by thfree** [comment]
ok, I will follow developments

**Comment by schaal** [comment]
A fix for this was just merged https://github.com/nextcloud/news/pull/43, should be available when Nextcloud News 9.0.5 is released.
