### ISSUE TITLE
Please add “mark read by scrolling“.

### ISSUE THREAD

**Issue by schaal** [schaal/ocreader#2]
Received via mail

**Comment by schaal** [comment]
I don't think that scrolling alone should change the state of an article. I'd rather change the "mark all as read" floating action button to only mark articles above the current scroll position as read.

**Comment by mourningsun75** [comment]
For me it did not work. When i press the button all articles are marked  as  read.

**Comment by schaal** [comment]
Already fixed via c81a87f, hopefully I'll get around to making a new release soon
