### ISSUE TITLE
Connect to nextcloud error

### ISSUE THREAD

**Issue by Darkmagister** [schaal/ocreader#21]
Hello, i've installed nextcloud 10 over owncloud, and reinstalled the news app (versione 9.0.4) that it's working on my server, but if i try to connect it via the ocreader app it's say:
Couldn't detect Nextcloud News version, check your owncloud setup

so, first why it's talk about owncloud, second why is that ? i inserted the root url of nextcloud it's ok ?

thanks for the support

**Comment by schaal** [comment]
It just says owncloud due to an outdated translation.

This is probably an issue with your installation. Sometimes the Nextcloud News version gets set to 0 after an update, by running:

```
occ config:app:set news installed_version x.x.x
```

with `x.x.x` replaced by your installed Nextcloud News version (e.g. `9.0.4`), you can fix the version number.

**Comment by schaal** [comment]
This should also be fixed by OCReader 0.19, as I don't check the version number anymore, only the supported API.

**Comment by Darkmagister** [comment]
ok, thanks for the info, but that commad doesn't work the correct one for me is otherwise it say too many argument:
occ config:app:set news installed_version --value 9.0.4
