### ISSUE TITLE
Nextcloud in subdirectory not found

### ISSUE THREAD

**Issue by Eloo** [schaal/ocreader#23]
If you use nextcloud in a subdirectory like `https://some.url:1234/nextcloud` the path after the host will be ignored and OCReader tells the user that nextcloud/owncloud could not be found.

**Comment by yvesf** [comment]
@schaal Would you mind making a new release so that the change could finally land in F-Droid?
The current version there is completely blocked for me because of this problem.

**Comment by yvesf** [comment]
@schaal 0.22 (from fdroid) works fine. Thank you.
