### ISSUE TITLE
Login fails reporting a malformed Json

### ISSUE THREAD

**Issue by alexl-kde** [schaal/ocreader#25]
Version 0.21. The login fails with the message: "Use JsonReader.setLenient(true) to accept malformed JSON at path $".
It worked with the previous 0.17 version.

**Comment by schaal** [comment]
Could you provide a logcat?

**Comment by alexl-kde** [comment]
It seems that nothing is added to logcat when I try to login. Is it possible?
Also, I can't check the version of Nextcloud News shipped by my provider. Maybe can this be caused by an old version of the server? Between 0.17 and 0.21 do you increase the minimum server version required?

**Comment by schaal** [comment]
There should be a stacktrace added to the logcat.

The minimum required Nextcloud News version increased to 8.8.0
You could check your version from the command line using:
```
curl -u USERNAME https://SERVER/index.php/apps/news/api/v1-2/status
```

**Comment by schaal** [comment]
Spoke too soon, I forgot to add the calls to log the error in the logcat, so there won't be anything in the logcat.

**Comment by alexl-kde** [comment]
Sorry I have the version 6. Should I close the bug until I can verify if with 8+ version will work?

**Comment by schaal** [comment]
I think this can be closed now, I also added a clearer error message when trying to login for this case.
