### ISSUE TITLE
com.squareup.moshi.JsonDataException: Expected a string but was NULL at path $.items[90].contentHash

### ISSUE THREAD

**Issue by papjul** [schaal/ocreader#26]
## Description of the issue
I have the exception `com.squareup.moshi.JsonDataException: Expected a string but was NULL at path $.items[90].contentHash` when synchronizing. No articles are retrieved.

## Expected behavior
Articles should be synchronizing and appearing in OCReader.

## Steps to reproduce

1. Touch "Synchronize"

## Your Environment

* OCReader version: 0.22 (not working since 0.19, was working with 0.17), from F-Droid repo
* Nextcloud news version: 9.0.4
* Android version: 5.1.1

### Logcat
```
com.squareup.moshi.JsonDataException: Expected a string but was NULL at path $.items[90].contentHash
```

**Comment by andre-dierker** [comment]
Same here with Stock Android 6.0.1

**Comment by schaal** [comment]
This seems more like a issue in [Nextcloud News](https://github.com/nextcloud/news) to me. The `contentHash` shouldn't be null. You could also try to run the command

```
sudo -u www-data php occ maintenance:repair
```

on your server.

If this doesn't help I'd suggest opening an issue with [Nextcloud News](https://github.com/nextcloud/news)

**Comment by papjul** [comment]
I ran the command, it didn't change anything.
Sync worked with 0.17, I updated few seconds after to 0.19 and it didn't work anymore, so this `contentHash` was added between 0.17 and 0.19 versions, so it doesn't seem like Nextcloud News is involved. What is it and could you make it optional? Or skip it if NULL value is found?

**Comment by schaal** [comment]
The contentHash is a way to identify specific articles. It is used to sync changes between the app and the server. It's not strictly necessary right now, but it will be once the sync API gets updated to v2. (See https://github.com/nextcloud/news/blob/master/docs/externalapi/External-Api.md#items for more information)

On versions prior to 0.18 the contentHash wasn't saved, so it went unnoticed when it was null. The contentHash is calculated on the server, so it is an issue with Nextcloud News.

Maybe you could mark the items as read on the web interface as a workaround?

**Comment by papjul** [comment]
Thanks for the explanations!
I'm not sure we should use it, it looks like it still a draft and I guess there are still articles on APIv1 for which contentHash has not been generated (I have starred and unread articles from 2 years ago).
I suggest we leave this issue opened until Nextcloud News final APIv2 has been released or it has been fixed on your side, so users in the same case can find this issue ;)

**Comment by schaal** [comment]
So it seems the contentHash is not yet generated for older items, I'll ignore it for now until it changes upstream.
