### ISSUE TITLE
Article is being brought to the top

### ISSUE THREAD

**Issue by sprnza** [schaal/ocreader#27]
## Description of the issue

When you switch between Ocreader and another app  article you read jumps from a position you was to the begining of it.
## Expected behavior

Position remains the same on an app switch.
## Steps to reproduce
1. Scroll in the middle of any article
2. Switch to another app
3. Switch back to Ocreader
4. See the beginning of the article
## Your Environment
- OCReader version: 0.22
- Nextcloud news version: 10.0.1
- Android version: 4.4.4

**Comment by sprnza** [comment]
*1. Scroll TO the middle...
Sorry...

**Comment by schaal** [comment]
Sorry for the late reply. I looked into how to solve this issue, but haven't found a decent solution yet.

**Comment by heyarne** [comment]
I was actually just looking into how to fix this myself. My (naive?) approach would be to save `contentHeight / scrollY` (so it also keeps the position when changing from portrait to landscape for example) as the instance state in `ItemPageFragment` and set the view up accordingly, is there anything wrong with that? If not I can look into it and submit a PR.

**Comment by schaal** [comment]
@heyarne I just pushed 236b15d which saves and restores the scroll position, it doesn't properly restore the position on orientation changes yet, feel free to improve that if you want ;-)

**Comment by doktorhorst** [comment]
I really like OCReader, but this makes reading long articles with links in it very uncomfortable. (no orientation change, just upright, OCReader 0.43, Android 6.0.1)

**Comment by znegva** [comment]
FYI: I can confirm this bug for version 0.52 (installed from FDroid, running on Android 10)
