### ISSUE TITLE
FAB: use "sync" instead of "mark as read"

### ISSUE THREAD

**Issue by tobiasKaminsky** [schaal/ocreader#28]
At least for my use case I use "sync" much more often than "mark as read" as I want to read/scroll all articles (and therefore they are marked as read already).
But to sync/refresh I have to scroll to top and do "pull to refresh" or open the sidemenu.
I do not like settings (and we avoid this on nextcloud android client), so maybe two floating action buttons are a way to go?

Thanks for this great app!

**Comment by schaal** [comment]
There are already two ways to start a sync as you mentioned, which I think are not too hard to access.
I don't like having multiple FABs and I don't see another fitting place for "mark as read" if I would move sync to the FAB. So I'm afraid I'll have to mark this as wontfix.

**Comment by tobiasKaminsky** [comment]
Ok, I can understand it :)
Thanks for your reply and keep up the good work :+1:

**Comment by schaal** [comment]
I got a similar request in #31 and solved it by switching the "mark all as read" FloatingActionButton with a sync button when it is pressed, so you just have to press it twice to sync when you are at the bottom of the list. I think this should also improve your use case.

**Comment by tobiasKaminsky** [comment]
Great! I am looking forward to the next version!
