### ISSUE TITLE
Since the last update the app often crashes

### ISSUE THREAD

**Issue by nrgeen** [schaal/ocreader#29]
## Description of the issue
The app crashes frequently when it updates the feed. Afterwards, she crashes at every opening. It will not work again until the app has been reset.
I had no problems with older apps.

## Expected behavior
The app should not crash.

## Steps to reproduce
I could not see the error. First I assumed that it is at a certain feed. But the error also appears after the complete removal of the feed.

## Your Environment

* OCReader version: 0.23
* Nextcloud news version: 9.0.4
* Android version: tested with 6.0.1 and 7.1

### Logcat
I complete the post with the log as soon as possible!

**Comment by schaal** [comment]
Could you try version 0.24 once it is published on f-droid? It fixes a crash related to favicon loading.

**Comment by nrgeen** [comment]
I'll test it an give an feedback.
Is there already a plan when the version appears?

**Comment by schaal** [comment]
I already released it, usually takes one or two days for it to appear on f-droid

**Comment by jrc2139** [comment]
great! I suffered the same issues and will report my exp with .24

**Comment by jrc2139** [comment]
working fine with 0.24. thanks for your work!

**Comment by nrgeen** [comment]
With version 0.24 the app runs again satisfactorily, too. Thank you very much!
