### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page; 0.1b2.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [schaal/ocreader#3]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not present, as of: 0.1b2.

**Comment by schaal** [comment]
Wating for the merge to be accepted:
https://gitlab.com/fdroid/fdroiddata/merge_requests/1228

**Comment by schaal** [comment]
And already accepted, that was fast!

**Comment by locutis-of-borg-1999** [comment]
:-)
