### ISSUE TITLE
[Request] Reload after Button "All read" pressed

### ISSUE THREAD

**Issue by amittel** [schaal/ocreader#31]
Hi!
When I'm done with looking at all the articles I press the button at the lower right corner.
Which in fact does not show up when I'm at the bottom. I have to scroll up a bit and it appears.
When pressed all articles are marked as read (from bold to normal font), but the list is not refreshed.
So I scroll all the way to the top and make a manual reload.

**Comment by schaal** [comment]
Now when pressing the "Mark all as read" FloatingActionButton in the right corner it turns into a sync button, so you can just press it again and don't have to scroll back up again to sync.
