### ISSUE TITLE
Feature Request: Expand Feeds in a Folder

### ISSUE THREAD

**Issue by Sortova** [schaal/ocreader#32]
## Description of the issue
When you look at the News feeds in Nextcloud, you'll see something like

News 56
  BBC 21
 CNN 19
 Register 16

But in OCReader it's:

News 56

with all of the feeds combined. I've done all the usual clicky things but I can't see to get the folder to expand so I can select the individual feeds like in the web client.

## Expected behavior

I would like to see all the folder collapse as it is now, but when you long press (or tap a twiddle, etc) the folder expands to show the individual feeds as in the Nextcloud webUI.

## Steps to reproduce
1) Launch OCReader
2) Tap the Menu
3) Look at the list of feeds

## Your Environment

* OCReader version: 0.24
* Nextcloud news version: 10.1.0
* Android version: 7.1

PS really nice app - clean and fast

**Comment by schaal** [comment]
If you select a folder on the left drawer you can swipe from the right to open a drawer there which shows the feeds of this folder.

**Comment by Sortova** [comment]
Ah, I was just writing an "I don't get it" but then I got it. Thanks.
