### ISSUE TITLE
'Mark All as Read' FAB disappears

### ISSUE THREAD

**Issue by lauhayden** [schaal/ocreader#34]
## Description of the issue
'Mark All as Read' FAB disappears and does not re-appear when expected. This leads to the user being unable to mark all articles as read without individually opening each article.

## Expected behavior
FAB should auto-hide when scrolling down, but unhide itself when scrolling back up

## Steps to reproduce
1. Open app (already logged in)
2. Pull-to-refresh
3. Open any article
4. Press 'back' to return to main activity - at this point the FAB is still visible
5. Scroll down - FAB disappears
6. When further scrolling up and down, FAB does not re-appear, even when refreshing or after opening and exiting another article

## Your Environment
OCReader: 0.25 (from FDroid)
Nextcloud News: 10.1.0
Android version: Android 7.1.1 Build NMF26F on Nexus 5X

### Logcat
Will post if requested

**Comment by schaal** [comment]
Related to https://code.google.com/p/android/issues/detail?id=230298

**Comment by lauhayden** [comment]
Hey, 0.26 isn't pushed to FDroid yet. I don't know how FDroid's backend works, so is it that you havne't uploaded it yet or it hasn't shown up yet? I'm just going to directly download the apk from here, but just FYI.

**Comment by schaal** [comment]
F-droid takes it directly from here, but sometimes it takes a couple days until it gets build there
