### ISSUE TITLE
Accept custom certificates

### ISSUE THREAD

**Issue by wwwi7891** [schaal/ocreader#36]
Is there any possibility of adding support for custom certificates? A lot of us are just using self signed ones for personal server and it's useful to still be able to connect over https.

**Comment by schaal** [comment]
Sorry, but I'm not going to add this. (See also #5)

You could either get a free certificate from [Let's Encrypt](https://letsencrypt.org) or add your certificate to the android user trust store. ([CADroid](http://cadroid.bitfire.at/) can help you import your certificate.)
