### ISSUE TITLE
New sidebar option: fresh articles

### ISSUE THREAD

**Issue by tobiasKaminsky** [schaal/ocreader#37]
On the sidebar it would be great to have a new entry "fresh articles" which only shows articles from the latest 24 hours.
Scenario: I have lots of lots articles, but want to read the latest 24 hours in the order "old -> new".

If you think this feature is worth implementing it, I can give it a try.

**Comment by schaal** [comment]
I think that sounds great. But instead of a new folder entry in the sidebar, I think a new menu entry to toggle between all and fresh would be better. This way it would work in any folder, not just unread. This could either be added to the sidebar, like the "only unread" option or the top menu.

**Comment by schaal** [comment]
On second thoughts, I think it makes more sense to have a new "fresh articles" entry in the sidebar like you suggested.

**Comment by tobiasKaminsky** [comment]
Great to hear.
I will try it next weekend.

**Comment by schaal** [comment]
Closed via #39
