### ISSUE TITLE
Let's Encrypt certificates not accepted

### ISSUE THREAD

**Issue by zkvvoob** [schaal/ocreader#38]
Hello,

I've got an ownCloud server which uses Let's Encrypt certificates, which renew ever 90 days of so. 

## Description of the issue
Today I decided to test OCReader, but could not even sign in, becasue the app kept displaying an error message;

"Couldn't verify certificate, please check your SSL setup".

## Expected behavior
SSL certificate accepted

## Steps to reproduce
1. Install OCReader
2. Open app
3. Enter server URL and credentials

## Your Environment

* OCReader version: 0.27
* Nextcloud news version: 9.0.4
* Android version: 6.0.1

Is this anything that could be remedied, please?
Thank you!

**Comment by schaal** [comment]
I'm also using a Let's Encrypt certificate and it works fine here.

Could you provide the logcat output when trying to login?

**Comment by zkvvoob** [comment]
I've got a logcat using adb on my computer, but even though I ran it for less than 5 seconds, it's huge. Is there a part of it which you need or should I add it entirely?

**Comment by schaal** [comment]
There should be a stack trace for a CertificateException, if you're not sure where to look, you can also send the whole logcat to ocreader@schaal.email

**Comment by Sortova** [comment]
Just another data point, but we use Let's Encrypt as well and it works fine.

**Comment by Eloo** [comment]
Yep working with Let's Encrypt here too. Works like a charm.

**Comment by schaal** [comment]
Thanks for the additional feedback. This seems to be a server issue not related to ocreader

**Comment by disanvparean** [comment]
I have the same problem. Let's encrypt certificate, with nginx.
Everything seems to work well with my browser and other apps connected securely.
Maybe it is related to the fact I use ddns.net domain.
Thank you

**Comment by schaal** [comment]
@disanvparean Would you be OK with sending me the URL to your server? This would help in figuring out what's wrong. You can send it to ocreader@schaal.email

**Comment by disanvparean** [comment]
Thank you but I think now it is now an OC reader related issue.
Indeed, where as Firefox has nothing to say about my certificate, I have the same errors with Nextcloud android app. I will check but my opinion is that it is related to no-ip.org service.

**Comment by schaal** [comment]
OK, thanks for the update, I'll close this again
