### ISSUE TITLE
State is not recovered

### ISSUE THREAD

**Issue by tobiasKaminsky** [schaal/ocreader#40]
When leaving the app while browsing "starred articles" the app should go into "starred articles" when re-opening the app (at least this is what the code suggests to me).

**Comment by schaal** [comment]
Yes, it's supposed to keep the currently selected folder. I also tried it on my phone and can't reproduce the problem, it restores the folder when reopening. Could you share the exact steps that lead to the problem so I can reproduce it?

**Comment by schaal** [comment]
Seems it restores every folder except "Fresh Articles" for me

**Comment by tobiasKaminsky** [comment]
- open app
- go to starred articles
- press back* -> closes app
- re-open app -> shows unread articles

\* I have found out that I am not allowed to press back, but instead I have to use the "middle" button which just suspends the app. Whit this, it also works with fresh articles for me.

**Comment by schaal** [comment]
I can reproduce it now, but don't know, why there is a difference between pressing the back and the home button. Will have to look into this.
