### ISSUE TITLE
Easy action to star an article

### ISSUE THREAD

**Issue by djibux** [schaal/ocreader#43]
I love the interface as it is, but I would love a quick way to star articles.  Pulling down on the article (just like you can pull to refresh on the list of articles) would be a great way to do that.

**Comment by schaal** [comment]
Do you mean on the article list or while reading an article? In the first case you can long-press an article and star it using the top toolbar, in the second case you can also star it using the toolbar.

I don't think that pulling down should be used to star an article, as it is not discoverable and pretty unusual.

**Comment by djibux** [comment]
I mean while reading an article. Any other way to do it would be fine but the icon at the top of the screen it too far to be convenient with one hand.  I would love to be able to slide from article to article and mark the ones I like with just one finger.

Le 13 février 2017 17:02:02 GMT+01:00, Daniel Schaal <notifications@github.com> a écrit :
>Do you mean on the article list or while reading an article? In the
>first case you can long-press an article and star it using the top
>toolbar, in the second case you can also star it using the toolbar.
>
>I don't think that pulling down should be used to star an article, as
>it is not discoverable and pretty unusual.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/schaal/ocreader/issues/43#issuecomment-279435285

-- 
djib

**Comment by schaal** [comment]
One way to improve this would be to add another floating action button at the bottom, I'll look into it.

**Comment by djibux** [comment]
Great, thanks.

Le 13 février 2017 18:14:20 GMT+01:00, Daniel Schaal <notifications@github.com> a écrit :
>One way to improve this would be to add another floating action button
>at the bottom, I'll look into it.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/schaal/ocreader/issues/43#issuecomment-279457363

-- 
djib
