### ISSUE TITLE
Use OwnCloud importer

### ISSUE THREAD

**Issue by rugk** [schaal/ocreader#45]
Currently on first run, you need to manually put in your credentials to the app. However it’s very likely that you already have the ownCloud app installed and hence the account can be reused there. This will dramatically ease the first run experience.

@David-Development of the ownCloud News app for Android built an awesome library for that: https://github.com/David-Development/ownCloud-Account-Importer

---

copied from https://github.com/stefan-niedermann/nextcloud-notes/issues/43 by @jancborchardt

**Comment by rugk** [comment]
I don't see how it is related to this issue here, but it is certainly a good idea.

**Comment by schaal** [comment]
> Actually since both @David-Development and @schaal here work on an Android News reader app for Nextcloud, I would suggest joining forces and working together. :)

There are actually some differences between them, @David-Development's app has more features (e.g. a podcast player), while I try to focus on a simple interface for just reading articles.

> We would be happy to give you a repository at https://github.com/nextcloud, for example »android-news«. :)

That would be awesome :-)

**Comment by schaal** [comment]
Re the actual issue:

I would rather like to see some form of OAuth implemented in Nextcloud to authenticate without having to enter the password in the app.

**Comment by rugk** [comment]
Yeah, that's what I propose in https://github.com/nextcloud/android/issues/748.

**Comment by schaal** [comment]
Unfortunately the account importer uses a different JSON serialization library as OCReader, so it is not compatible.

From version 0.45 on, OCReader instead uses the Nextcloud Login Flow, which delegates login to the web interface and returns a new Apptoken for OCReader.
