### ISSUE TITLE
New logo/icon design

### ISSUE THREAD

**Issue by tapir** [schaal/ocreader#47]
Yesterday I've come across this reddit [thread](https://github.com/schaal/ocreader) and I've took the liberty to contact the guys for a new logo/icon for OCReader. Are you interested in one? I think ocreader could use one.

**Comment by schaal** [comment]
Which thread are you referring to? You seem to have pasted the wrong link.

**Comment by tapir** [comment]
Sorry about that.
https://www.reddit.com/r/opensource/comments/615udp/my_graphic_design_buddy_is_looking_to_make_some/

**Comment by tapir** [comment]
As I said I've already contacted the guy. We can invite him to this issue if you're up for a new logo. Just let me know.

**Comment by schaal** [comment]
Thanks for the offer, but I think I'll stick with the current logo for now
