### ISSUE TITLE
Accept self-signed certificates

### ISSUE THREAD

**Issue by Exel232** [schaal/ocreader#5]
Please include the option to accept self-signed certificates. Currently it will exit with a trust anchor problem.

**Comment by schaal** [comment]
I'd like to avoid that if possible.

Is it possible for you to get a free certificate from [Let's Encrypt](https://letsencrypt.org)?
Alternatively you could try [CADroid](http://cadroid.bitfire.at/) to import your certificate into the system trust store.

**Comment by Exel232** [comment]
I am currently using dynamic dns. As lets encrypt has registration limits for domains. It is almost impossible to get a certificate for such an address. I already imported my certificate, but it didnt work correctly.

**Comment by schaal** [comment]
Turns out that depending on your ddns provider, you can get a certificate from lets encrypt, if it is on the public suffix list: https://github.com/letsencrypt/letsencrypt/issues/1607#issuecomment-159168888

**Comment by schaal** [comment]
I just reverted the integration of MemorizingTrustManager and the app therefore doesn't accept self-signed certs anymore (starting with the next release probably). It just opens too many security issues. Also MemorizingTrustManager isn't maintained anymore, which is not good for security related code. (It's also recommended by owncloud news maintainer to disable cert checking: https://github.com/owncloud/news/blob/master/docs/developer/External-Api.md#security-guidelines).

**Comment by ilpianista** [comment]
I updated to Nougat and it seems that CACert is not accepted even if I installed it?

**Comment by schaal** [comment]
Do other apps accept CACert certificates? I use the trust store provided by android, so it should work if it is correctly installed.

**Comment by ilpianista** [comment]
DAVDroid does and I just saw that they switched from [MemorizingTrustManager to cert4android](https://gitlab.com/bitfireAT/davdroid/commit/19ab4a14ce9adf9f3e8f91571939fb4647ee51e1).

**Comment by schaal** [comment]
Thanks for the pointer. It seems I have to add a [network security config](https://developer.android.com/training/articles/security-config.html) for Android 7 to accept user-installed certificates, will look into this

**Comment by schaal** [comment]
@ilpianista Just released version 0.27 which adds the necessary configuration to accept user added CAs again, should be on F-Droid in the next couple days

**Comment by ilpianista** [comment]
Great! Thank you!
