### ISSUE TITLE
Night mode doesn't work the first time entering the item pager

### ISSUE THREAD

**Issue by schaal** [schaal/ocreader#50]
For some reason, ItemPagerActivity has wrong NIGHT_MODE setting the first time it is started when the dark theme is selected. The second time, the correct NIGHT_MODE value is set.

**Comment by Eloo** [comment]
can confirm this

**Comment by operat** [comment]
For me, the problem didn't occur before. It exists since I switched to LineageOS (v14.1, Android v7.1.2) and OCReader v0.38.

**Comment by eloo** [comment]
i'm on lineageOS too
