### ISSUE TITLE
http stream was reset during refresh

### ISSUE THREAD

**Issue by fvzwieten** [schaal/ocreader#51]
## Description of the issue

More often than not I get this error while refreshing the articles:
okhttp3.internal.http2.streamRe.setException stream was reset:INTERNAL_ERROR 

## Expected behavior

It should simply refresh the articles and show any new articles when available

## Steps to reproduce

This part is unclear. I can describe the steps to get it working again for some time:
1. On Android: stop ocreader, clear cache, clear data
2. On Nextcloud, mark all articles as read
3. On Android, set up ocreader as a new app: login to nextcloud.

## Your Environment

* OCReader version:
0.29

* Nextcloud news version:
11.0.2

* Android version:
7.1.1

### Logcat
(Read http://www.makeuseof.com/tag/get-logcat-reporting-bugs-android/ if you are not sure how to get the logcat output.)

```
Please paste the relevant logcat output here
```

**Comment by schaal** [comment]
Thanks for the report, sounds like a bug in okhttp, but hard to tell without a logcat. Would it be possible for you to add this information here?

**Comment by fvzwieten** [comment]
It's not happening anymore, somehow. Now idea why. I it start again, I will try to make a logcat.

**Comment by schaal** [comment]
Thanks for the update, feel free to reopen if this occurs again.
