### ISSUE TITLE
OCReader fails to load/sync with News after Nextcloud app update

### ISSUE THREAD

**Issue by operat** [schaal/ocreader#52]
## Description of the issue

I updated the Nextcloud News app to 10.2.0 (configuration of OCReader apps on my Android devices remained untouched). After the update, OCReader doesn't load/sync with Nextcloud News, but throws the following error instead:

com.squareup.moshi.JsonDataException: Expected a long but was NULL at path: $.items[*].updatedDate

In place of the * appears a number, depending on what category or device you are in/on.

## Expected behavior

OCReader should load/sync with Nextcloud News, no matter what version is installed.

## Steps to reproduce

Open OCReader app on Android device, go to Unread Articles and try to update/sync.

## Your Environment

OCReader version: 0.29
Nextcloud news version: 10.2.0
Android version: 4.4.4 and 4.2.2

**Comment by schaal** [comment]
Already fixed in release 0.32, unfortunately not yet available from FDroid
