### ISSUE TITLE
OCreader does not sync after News 10.2.0 update

### ISSUE THREAD

**Issue by tterranigma** [schaal/ocreader#53]
## Description of the issue
When I hit synchronize I get an error:
"com.squareup.moshi.JsonDataException: Expected a long but was NULL at path $.items[8].updatedDay"

* OCReader version: 11.0.2
* Nextcloud news version: 10.2.0
* Android version: 6.0.1

**Comment by escoand** [comment]
Can confirm this on OCReader 0.31 and Android 7.0

**Comment by escoand** [comment]
Is #52 the correct solution for this?

**Comment by tterranigma** [comment]
hm, it seems yes. I missed the #52 , I only went through the open issues. Clsoing.
