### ISSUE TITLE
http stream was reset during refresh

### ISSUE THREAD

**Issue by fvzwieten** [schaal/ocreader#58]
## Description of the issue

More often than not I get this error while refreshing the articles:
okhttp3.internal.http2.streamRe.setException stream was reset:INTERNAL_ERROR

## Expected behavior

It should simply refresh the articles and show any new articles when available

## Steps to reproduce

This part is unclear. I can describe the steps to get it working again for some time:

    On Android: stop ocreader, clear cache, clear data
    On Nextcloud, mark all articles as read
    On Android, set up ocreader as a new app: login to nextcloud.

## Your Environment

    OCReader version:
    0.29

    Nextcloud news version:
    11.0.2

    Android version:
    7.1.1

### Logcat
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: Failed to execute sync callables
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: java.util.concurrent.ExecutionException: okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at java.util.concurrent.FutureTask.report(FutureTask.java:94)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at java.util.concurrent.FutureTask.get(FutureTask.java:164)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at email.schaal.ocreader.api.APIv12$3$1.run(APIv12.java:365)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at java.lang.Thread.run(Thread.java:761)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: Caused by: okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at okhttp3.internal.http2.Http2Stream$FramingSource.checkNotClosed(Http2Stream.java:436)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:338)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at okio.ForwardingSource.read(ForwardingSource.java:35)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at okio.RealBufferedSource.read(RealBufferedSource.java:45)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at okio.ForwardingSource.read(ForwardingSource.java:35)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at retrofit2.OkHttpCall$ExceptionCatchingRequestBody$1.read(OkHttpCall.java:285)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at okio.RealBufferedSource.indexOfElement(RealBufferedSource.java:363)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at okio.RealBufferedSource.indexOfElement(RealBufferedSource.java:352)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at com.squareup.moshi.JsonUtf8Reader.nextQuotedValue(JsonUtf8Reader.java:784)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at com.squareup.moshi.JsonUtf8Reader.nextString(JsonUtf8Reader.java:589)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at email.schaal.ocreader.api.json.ItemTypeAdapter.fromJson(ItemTypeAdapter.java:101)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at email.schaal.ocreader.api.json.ItemTypeAdapter.fromJson(ItemTypeAdapter.java:44)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:75)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:52)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:127)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:204)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:166)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:127)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:34)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:42)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:25)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:118)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:212)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:89)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at email.schaal.ocreader.api.APIv12$UpdatedItemsCallable.getResponse(APIv12.java:480)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at email.schaal.ocreader.api.APIv12$RealmCallable.call(APIv12.java:421)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at email.schaal.ocreader.api.APIv12$RealmCallable.call(APIv12.java:409)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-19 20:28:05.935 21236 21270 E email.schaal.ocreader.api.APIv12: 	... 3 more
04-19 20:28:05.958 21236 21236 D email.schaal.ocreader.service.SyncService: email.schaal.ocreader.action.SYNC_FINISHED: FULL_SYNC
04-19 20:28:06.080  4403  4403 D KP2AAF  : OnAccEvent
04-19 20:28:06.205  4403  4403 D KP2AAF  : OnAccEvent
04-19 20:28:06.206  4403  4403 D KP2AAF  : event: 2048, package = email.schaal.ocreader
04-19 20:28:06.206  4403  4403 D KP2AAF  : no com.android.systemui
04-19 20:28:06.215  4403  4403 D KP2AAF  : Cancel notif
04-19 20:28:06.378  4398  4398 I TWILIGHT: [20:28:06.378, main]: Accessibility CHANGED email.schaal.ocreader android.support.v4.widget.DrawerLayout
04-19 20:28:06.383  4398  4398 I TWILIGHT: [20:28:06.383, main]: package email.schaal.ocreader

**Comment by fvzwieten** [comment]
Every time I refresh in ocreader and this error occurs, I see this line in my /var/log/nginx/error.log:

2017/05/02 21:54:23 [crit] 10631#0: *394 open() "/var/lib/nginx/tmp/fastcgi/3/01/0000000013" failed (13: Permission denied) while reading upstream, client: <ip address android phone>, server: <my fqdn>, request: "GET /index.php/apps/news/api/v1-2/items/updated?lastModified=1493700277&type=3&id=0 HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "<my fqdn>"

**Comment by fvzwieten** [comment]
I tracked this down to being an issue with nginx as the webserver for nextcloud. I switched back to Apache and now this issue doesn't happen anymore. So I am not sure this is something that needs to be fixed in ocreader is is because of a configuration issue on the nginx webserver implementation.

**Comment by schaal** [comment]
Thanks for the update, I don't think there is anything to be done on the ocreader side
