### ISSUE TITLE
only one article 

### ISSUE THREAD

**Issue by alex1702** [schaal/ocreader#6]
I have for example 5 New news. But in the unread list is only one entry. If i read this article and reload a New of the 5 news will shown but only one. Not all article. And unread number Fall to 4.
In the other section it will also only show one Entry.
Two Screenshots: https://p.elaon.de/m-Hqc/

**Comment by schaal** [comment]
I have also encountered this, but haven't found the cause yet. A workaround is to mark the missing articles as read on the webinterface.

**Comment by steppy** [comment]
Occurs for me as well. Other than that the app is nice and also runs on BB10 (the "official" one does not).

**Comment by schaal** [comment]
Thanks, but I still couldn't figure out what causes this issue, I thought it was related to the automatic syncing of article states, but couldn't reproduce it yet when debugging

**Comment by schaal** [comment]
I just pushed a new release (0.7) with some changes to the syncing mechanism (see 76a694f6c56d9c538996d6581549d90fb2d409ac and 38d8835a6de866623a85e417d9c4fb4296a84848) to address this issue. I have been running this for a couple days without this issue popping up again, but as this bug occurs so infrequently, I can't be sure it is fixed yet.

**Comment by alex1702** [comment]
i will test, if i can update over fdroid.

**Comment by steppy** [comment]
Unfortunately, the issue is still present in 0.7 for me.

**Comment by schaal** [comment]
I just pushed a commit, which makes the synchronisation of article states non-parallel, hopefully this improves things

**Comment by alex1702** [comment]
I think it is owncloud 8 (8.2.3) respectively the news APP Version. Today i updatet to owncloud 9 and ocreader works fine.

**Comment by schaal** [comment]
This also doesn't happen for me anymore, so I assume it is finally fixed
