### ISSUE TITLE
Feed is not fetched due to JSON error

### ISSUE THREAD

**Issue by heyarne** [schaal/ocreader#63]
## Description of the issue

The feed doesn't get fetched because of wrong assumptions about the returned JSON. More precisely, I get a toast complaining about `updatedDate` being `null` and not a `long`, which causes no items to be displayed at all.

## Expected behavior

It should not assume that there is an `updatedDate` on all items or provide a sensible default value maybe.

## Steps to reproduce

I currently can not reproduce what feed item exactly raises the error. I will try to provide additional info as soon as I have the time.

## Your Environment

* OCReader version: 0.31
* Nextcloud news version: Most recent
* Android version: 7.1.2
* Nextcloud version: 11.0.3

### Logcat
(Read http://www.makeuseof.com/tag/get-logcat-reporting-bugs-android/ if you are not sure how to get the logcat output.)

```
Please paste the relevant logcat output here
```

**Comment by schaal** [comment]
Could you try updating OCReader? This should already be fixed in version 0.33

**Comment by heyarne** [comment]
Yes, updating fixed it, thanks a lot for all of your effort and for your quick response, I love the app and use it daily!
