### ISSUE TITLE
Couldn't verify certificate, please check your SSL setup !!

### ISSUE THREAD

**Issue by vincegre** [schaal/ocreader#64]
## Description of the issue
 App refuses to connect at my NextCloud instance stating it couldn't verify SSL certificate (tried filling adress with or without https:// in front but same)

## Expected behavior

Should connect at my instance

## Steps to reproduce

1. Tiped adress of my NextCloud instance (the SSL certificate is generated by Let's Encrypt)
2.
3.

## Your Environment

* OCReader version: 0.34
* Nextcloud news version: NextCloud 11.0.3 News app version: 10.2.0
* Android version: 7.1.1

Thanks

Vincèn

**Comment by schaal** [comment]
Does it work if you access your server using a browser?

**Comment by vincegre** [comment]
@schaal works perfectly fine in browser and with other aps that connect with my Nextcloud install !!

**Comment by schaal** [comment]
Do you still have this issue with a newer OCReader version?

**Comment by schaal** [comment]
Please reopen if you still have this issue
