### ISSUE TITLE
Can't login using an app password on Nextcloud 12

### ISSUE THREAD

**Issue by HanFox** [schaal/ocreader#66]
## Description of the issue
When I try to login with the correct credentials OCReader complains that the user/password is incorrect. Other apps, such as the desktop client login correctly.

I've disabled BruteForce checks for my home IP address.

Pretty sure TOTP app password login worked with Nextcloud 11, so I suspect a change to NC's API may be to blame?

## Expected behaviour
OCReader will login.

## Steps to reproduce
1. Enable TOTP / 2FA in Nextcloud 12 (https://github.com/nextcloud/twofactor_totp)
2. Generate an app password
3. Fill in details in OCReader
4. Try and login

## Your Environment
* OCReader version: 0.35 and 0.34
* Nextcloud news version: 12.0.0
* Android version: 7.1.2

**Comment by schaal** [comment]
Just tried this and it works fine for me. Is there any output in your nextcloud log about this login attempt?

**Comment by HanFox** [comment]
Erm, so it works fine now... I had fought with it for a couple of days and it flat out refused with a relative normal "login failed" error.

I can only guess I had some sort of setup issue on the server that resolved it. Oops.
