### ISSUE TITLE
Connection attempt to 4.bp.blogspot.com?

### ISSUE THREAD

**Issue by gadgetguy08** [schaal/ocreader#68]
## Description of the issue
App attempts to connect to 4.bp.blogspot.com

## Expected behavior
Not sure why it is attempting to go there.

## Steps to reproduce

1. Starting to use app
2.
3.

## Your Environment

* OCReader version: 0.35
* Nextcloud news version: 11
* Android version: 6.0.1

### Logcat
(Read http://www.makeuseof.com/tag/get-logcat-reporting-bugs-android/ if you are not sure how to get the logcat output.)

```
Please paste the relevant logcat output here
```

**Comment by schaal** [comment]
It probably tries to download the favicon for a feed of yours, as this app doesn't make any other connection attempts (other than your nextcloud instance).

**Comment by schaal** [comment]
I think this issue is resolved, if you have further questions about this, don't hesitate to ask
