### ISSUE TITLE
JsonDataException expected a string but was null at path $.items[6].fingerprint

### ISSUE THREAD

**Issue by samweisgamdschie** [schaal/ocreader#69]
## Description of the issue
I get following message when trying to sync news:
JsonDataException expected a string but was null at path $.items[6].fingerprint

## Expected behavior
Get my news synced

## Steps to reproduce
1.add Server with user and pw
2.pull down
3.only get my folders but not my feeds and no news synced.
4. get this exception

## Your Environment

* OCReader version:0.36
* Nextcloud news version:11.0.2
* Android version: 6.0.1

### Logcat
I actally cant get the logcat output, will deliver it, when I am able to.

**Comment by schaal** [comment]
That seems to be a problem with nextcloud or the nextcloud news app, as the fingerprint should never be null. I'll look into whether I can find a workaround for this issue.
