### ISSUE TITLE
method not allowed

### ISSUE THREAD

**Issue by bestouff** [schaal/ocreader#7]
Hi, since a few versions I had only 1 unread article with this app. I just tried erasing all data and configuring it again, but now I can't login anymore, I'm greeted with a "method not allowed" instead.

**Comment by schaal** [comment]
This sounds like a server issue. Could you try this from the command line:

`curl --basic --user <USERNAME> https://<OWNCLOUD_URL>/index.php/apps/news/api/v1-2/status`

to see if the news app is setup properly.

Otherwise I'd need a logcat to see what's wrong.

**Comment by bestouff** [comment]
That prompts for a password, and then nothing.

**Comment by schaal** [comment]
ok, that should output your owncloud news version (something like `{"version":"8.7.5","warnings":{"improperlyConfiguredCron":false}}`, so it indeed looks like there's something wrong with your owncloud setup.

**Comment by bestouff** [comment]
I added -D to dump the headers. If I get /owncloud/ I get a 302, but your URI gets me a 405:
```
[xav@pcxav:~/canbus]$ curl --basic -D - --user xav https://awak.mobi/owncloud/
Enter host password for user 'xav':
HTTP/1.1 302 Found
Date: Fri, 13 May 2016 16:12:21 GMT
Server: Apache/2.4.10 (Debian)
X-Powered-By: PHP/5.6.20-0+deb8u1
Set-Cookie: oc2f99543cd7=br26iec8n4vitteh5mge105ur4; path=/owncloud; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Strict-Transport-Security: max-age=31536000
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *
X-Robots-Tag: none
Set-Cookie: oc2f99543cd7=0g321bseovm095d5lnar0s6q31; path=/owncloud; secure; HttpOnly
Location: https://awak.mobi/owncloud/index.php/apps/files/
Content-Length: 0
Content-Type: text/html; charset=UTF-8

[xav@pcxav:~/canbus]$ curl --basic -D - --user xav https://awak.mobi/owncloud/index.php/apps/news/api/v1-2/status
Enter host password for user 'xav':
HTTP/1.1 405 Method Not Allowed
Date: Fri, 13 May 2016 16:14:42 GMT
Server: Apache/2.4.10 (Debian)
X-Powered-By: PHP/5.6.20-0+deb8u1
Set-Cookie: oc2f99543cd7=5mlleadv0olb3jbr1ef9jhk5c5; path=/owncloud; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Strict-Transport-Security: max-age=31536000
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *
X-Robots-Tag: none
Set-Cookie: oc2f99543cd7=162v5gd4ll63up9h6vfop1apf0; path=/owncloud; secure; HttpOnly
Content-Length: 0
Content-Type: text/html; charset=UTF-8
```

**Comment by bestouff** [comment]
FWIW before I erased the app's data, it worked (with 1 news item only) but there was always that little round grey window saying "405 Method Not Allowed" when refreshing.

**Comment by schaal** [comment]
You could check your owncloud log, or check if the owncloud news app is correctly installed

**Comment by bestouff** [comment]
(Sorry for spamming with comments) I tried one more thing: `https://awak.mobi/owncloud/index.php/apps/news/api/v1/status` gets me a 302, so maybe the problem is that I use Debian which only has Owncloud 7.

**Comment by bestouff** [comment]
`owncloud.log` is full of
```
{"app":"news","message":"Configuration value \"simplePieCacheDuration\" does not exist. Ignored value.","level":2,"time":"2016-05-13T16:11:42+00:00"}
```
nothing more.

**Comment by schaal** [comment]
Yes that's the problem, OCReader only supports API version v1-2, I believe the official [official client](https://github.com/owncloud/News-Android-App) also supports the v1 api

I should propably add a better error message for this case
