### ISSUE TITLE
Feature request: Per-feed list

### ISSUE THREAD

**Issue by shtrom** [schaal/ocreader#75]
## Description of the issue
It seem ocReader can only show one unified feed per category, collating the entries from all the feeds.

## Expected behavior
I should be able to select a single feed in a category, and only see its entries.

**Comment by schaal** [comment]
That's actually already possible by selecting the folder and then swiping in from the right, which opens a drawer with a list of the feeds in this folder.

**Comment by shtrom** [comment]
On Tue 26 Sep 2017 at 05:19:50 +0000, Daniel Schaal wrote:
> That's actually already possible by selecting the folder and then swiping in from the right, which opens a drawer with a list of the feeds in this folder.

Ah! Cool. It wasn't obvious from the UI, but that's exactly what I was
after.

Thanks.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.
