### ISSUE TITLE
OCReader hangs on swiping between articles

### ISSUE THREAD

**Issue by oldnomad** [schaal/ocreader#77]
## Description of the issue
OCReader hangs (freezes) when swiping left/right between articles. Given sufficient number of articles (for me, around 15 on BBC News feed, for example), swiping between them without returning to the feed makes OCReader to hang (freeze) on partially swiped-in article. The screen shows the new article almost at the center, with one margin slightly larger. I've found no crash report in logcat.

The effect seems to appear in version 0.38, at least I don't remember such freezes happening in previous version.

## Expected behavior
OCReader shouldn't hang.

## Steps to reproduce
1. Open a feed with sufficient number of articles. Longer articles seem to give the effect sooner.
2. Open the first article.
3. Swipe to the next article several times.
4. After several swipes OCReader hangs. The effect is unstable, seems to require different number of swipes.

## Your Environment

* OCReader version: 0.38 (41)
* Nextcloud news version: 10.2.0
* Android version: 5.1.1

### Logcat
The freeze doesn't seem to produce any relevant logcat information.

**Comment by schaal** [comment]
Thanks for the report, can't reproduce this yet here, but will look into it.

**Comment by schaal** [comment]
Version 0.45 uses the new ViewPager2 implementation, please reopen if this issue still persists.
