### ISSUE TITLE
Don't show "Mark as read" button when no articles are available

### ISSUE THREAD

**Issue by moritz-weber** [schaal/ocreader#78]
## Description of the issue
"Mark as read" button is visible, even without any available articles. See screenshot:
![screenshot_20171121-104017](https://user-images.githubusercontent.com/17176771/33070946-f7674968-ceb9-11e7-85fc-7a1150d742fb.png)

It's really just a minor issue, but I think the current implementation doesn't make sense. 

## Expected behavior
Don't transition from "Reload" button to "Mark as read" button when no new articles are available.

## Steps to reproduce
1. Fetch new articles
2. Mark them as read
3. Fetch again => 

## Your Environment

* OCReader version: 0.38
* Nextcloud news version: 11.0.5
* Android version: 7.0

**Comment by schaal** [comment]
The Floating Action Button was replaced with a Bottom App Menu in version 0.45, which has menu items for both syncing and marking all as read.
