### ISSUE TITLE
Crash reports leak password

### ISSUE THREAD

**Issue by felmab** [schaal/ocreader#87]
## Description of the issue

The stack trace contains all credentials to log in to the Nextcloud instance, including a password:
<pre>
...
"SHARED_PREFERENCES": {
  "default": {
    "password": "[REDACTED]",
    "order": "DESCENDING",
    "sort_field": "id",
    "is_sync_running": false,
    "url": "[REDACTED]",
    "dark_theme": false,
    "needs_update_after_sync": false,
    "detected_api_level": "v1-2",
    "acra.legacyAlreadyConvertedToJson": true,
    "acra.legacyAlreadyConvertedTo4.8.0": true,
    "username": "[REDACTED]",
    "show_only_unread": true,
    "acra.lastVersionNr": 43
   }
 }
...
</pre>

IMHO sending sensitive information should be avoided.

## Your Environment

* OCReader version: 0.39
* Nextcloud news version: 11.0.5
* Android version: 7.1.2

**Comment by schaal** [comment]
Oh my god! I updated ACRA (the library used to report crashes), but didn't release that the new version includes the shared preferences by default. I changed this now to only include the stack trace (which contains no personal information), the android version and the user comment. I also deleted all crash reports that I received.

**Comment by felmab** [comment]
Thank you @schaal for such a quick fix!

Ideally users should be advised to change their Nextcloud password if they sent a crash report in the past, since it was sent by email, which is by default an insecure protocol.

**Comment by schaal** [comment]
> Ideally users should be advised to change their Nextcloud password if they sent a crash report in the past

I made a new release (v0.43) which displays a one-time warning about this when starting the app with a recommendation to change the password and a link to this page: https://github.com/schaal/ocreader/wiki/Information-about-possible-password-leak

**Comment by felmab** [comment]
Neat!

Thanks a lot for your work.
