### ISSUE TITLE
On resume: reader looses it read state in an article

### ISSUE THREAD

**Issue by tobiasKaminsky** [schaal/ocreader#88]
## Description of the issue
- article is shown from beginning

## Expected behavior
- remember state of article

## Steps to reproduce

1. open an article
2. read it, to e.g. 50%
3. hide app
4. resume app
5. see article starting from beginning

## Your Environment

* OCReader version: latest play store version
* Nextcloud news version: 13
* Android version: 8.1

Hopefully I remember right that this was working some time ago.
If it is indeed a regression, I am happy to debug it.

**Comment by schaal** [comment]
> Hopefully I remember right that this was working some time ago.

Yes, that is a regression. I fixed this in https://github.com/schaal/ocreader/commit/236b15df7b03258abd82cb9477247ccc191f1cd6, so it should restore the read progress when resuming the app. It doesn't yet restore it when rotating.

> If it is indeed a regression, I am happy to debug it.

That would be great, thanks
