### ISSUE TITLE
[FR] Add Single sign-on

### ISSUE THREAD

**Issue by fazlerabbi37** [schaal/ocreader#93]
It would be great if you could add single sign-on as an option in addition to the traditional login. This is one of the very few android apps that is not using SSO in the Nextcloud ecosystem.

see more: https://github.com/nextcloud/Android-SingleSignOn

**Comment by schaal** [comment]
Thanks for the suggestion.

Unfortunately the SingleSignOn library uses a different JSON serialization library as OCReader, so it is not compatible.

From version 0.45 on, OCReader instead uses the Nextcloud Login Flow, which delegates login to the web interface and returns a new Apptoken for OCReader.
